apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-mcp-server-service
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
spec:
  selector:
    app: mcp-server
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: {{ .Values.mcpServer.service.type }}